//<![CDATA[
function zh1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/rcti" } 
function zh2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/gtv" }
function zh3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mnctv" } 
function zh4(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/inews" } 
function zh5(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/antv" } 
function zh6(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/transtv" } 
function zh7(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/trans7" } 
function zh8(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tvone" } 
function zh9(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/metro" }
function zh10(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/rtv" } 
function zh11(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/kompas" } 
function zh12(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tvri" }
function zh13(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/jaktv" }
function zh14(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/jtv" }
function zh15(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/balitv" }
function zh16(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/daaitv" }
function zh17(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/bandungtv" }
function zh18(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/nettv" }
function mncnews(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncnews" }
function cnn(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/cnn" }
function beritasatu(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/beritasatu" }
function dw(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/dw" }

<!--Entertainment-->

function zh19(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/musictv" }
function zh20(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncie" }
function zh21(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/visionprime" }
function zh22(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncent" }
function zh23(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/oktv" }
function zh24(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/axn_id" }
function zh25(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/animax_id" }
function zh26(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/kix_id" } 
function zh27(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/warnertv_id" }
function zh28(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tvn_id" } 
function zh29(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/one_id" } 
function zh30(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/lifetime_id" } 

function kidstv(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/kidstv" }
function nickjr(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/nickjr_id" } 
function boomerang(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/boomerang_id" }
function cbeebies(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/cbeebies" } 
function cartoon(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/cn_id" } 
function nick(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/nickelodeon_id" } 
function natgeo(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/natgeo_id" } 
function ngeowild(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/ngeowild_id" } 
function aplanet(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/aplanet_id.html" } 
function discovery(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/discovery_id" } 

<!--Sports-->
function zh31(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/spotvhd" } 
function zh32(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/spotv2" } 
function zh33(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncsport1" } 
function zh34(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncsport2" }
function zh35(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/mncsport3" } 
function zh36(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/soccerhd" } 

function bein1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/bein" }
function bein2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/bein2" }
function bein3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/bein3" }
function bein33(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/beinsport3" }
function euro1de(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/euro1de" }
function euro2de(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/euro2de" }
function euro1es(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/euro1de" }
function euro2es(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/euro2de" }
function dazn1de(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/1de" }
function dazn2de(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/2de" }
function dazn1es(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/1de" }
function dazn2es(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/dazn2de" }
function laligaes(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/laligaes" }
function sportsdigital(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/sportsdigital" }
function zonait(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/dazn/zonait" }
function cplus1pl(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/cplus1pl" }
function cplus2pl(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/cplus2pl" }
function cplus3pl(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/cplus3pl" }
function eleven1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/eleven1" }
function eleven2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/eleven2" }
function eleven3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/eleven3" }
function eleven4(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/eleven4" }

function polsatpre1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/polsatpre1" }
function polsatpre2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/polsatpre2" }
function laligatv(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/movistarlaliga" }
function laligatv1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/sport/movistarlaliga1" }
function sonytenhd1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonytenhd1.m3u8" }
function sonytenhd2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonytenhd2.m3u8" }
function sonytenhd3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonytenhd3.m3u8" }
  
 function sonyten1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonyten1.m3u8" }
function sonyten2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonyten2.m3u8" }
function sonyten3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/player.html?file=/sport/sonyten3.m3u8" }





function zh37(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hits_id" }
function zh38(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hitsmovies_id" }
function zh39(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tv5monde" }
function zh40(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/jiangsuntv" }
function zh41(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hunantv" }
function zh42(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/shanghaitv" }
function zh43(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/xingkongtv" }
function zh44(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/anhuitv" }

function sctv(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/sctv" }
function indosiar(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/indosiar" }

<!--Movie-->
function thrill(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/thrill" }
function cm(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/cm" }
function ccm(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/ccm" }
function zeebioskop(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/zeebioskop" }
function tvnmovie(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tvnmovie_id" }
function cinemax(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/cinemax_id" }
function hitsmovies_id(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hitsmovies_id" }

function hbo1(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hbo_id" }
function hbo2(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hbofamily_id" }
function hbo3(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hbohits_id" }
function hbo4(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/hbosignature_id" }
function imc(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/imc" } 
<!--Religion-->
function muslimtv(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/muslimtv" } 
function life(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/life" } 
function alquran(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/alquran" } 
function tvmu(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tvmu" } 
function tawaftv(){document.getElementById("tv")
.src="https://tv.iframe.eu.org/lokal/tawaftv" } 
//]]>
